name: Deploy to AWS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 43.201.205.65
        username: ubuntu
        key: ${{ secrets.AWS_SSH_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/HorizonSeaweed
          git pull
          npm install --production
          npm run build
          pm2 reload horizonseaweed || pm2 start npm --name horizonseaweed -- start
          pm2 save